[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/src/main.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/App.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/index.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"


